/*
 * Event Portal Open API
 *
 * REST API Concepts  Solace PubSub+ Event Portal provides REST APIs that you can use to manage your data in PubSub+ Cloud.  The REST APIs allow you to model your event-driven architectures from your own client applications.  The following document describes the public REST APIs available for use in Event Portal 2.0. Objects created in this  version will not be available in Event Portal 1.0. APIs that display (Beta) in their summary are provided as-is and  are subject to change or removal. They may not be of the quality expected for generally available APIs and have no  guaranteed forward compatibility with the generally available version of the API.  
 *
 * API version: 2.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventManagementAgentRegion struct {
	// Primary key set by the server.
	Id string `json:"id,omitempty"`
	// The id of the service from maas-core.
	ServiceId string `json:"serviceId"`
	// The name of the EventManagementAgentRegion.
	Name string `json:"name"`
	// The name of the cloud provider.
	CloudProvider string `json:"cloudProvider"`
	// The name of the region.
	Region string `json:"region"`
	// The host name of the region.
	Host string `json:"host"`
	// The name of the region's msgVpn.
	MsgVpn string `json:"msgVpn"`
	// The SMF port number.
	Port int32 `json:"port,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	UpdatedBy string `json:"updatedBy,omitempty"`
	CreatedTime string `json:"createdTime,omitempty"`
	UpdatedTime string `json:"updatedTime,omitempty"`
}
