/*
 * Event Portal Open API
 *
 * REST API Concepts  Solace PubSub+ Event Portal provides REST APIs that you can use to manage your data in PubSub+ Cloud.  The REST APIs allow you to model your event-driven architectures from your own client applications.  The following document describes the public REST APIs available for use in Event Portal 2.0. Objects created in this  version will not be available in Event Portal 1.0. APIs that display (Beta) in their summary are provided as-is and  are subject to change or removal. They may not be of the quality expected for generally available APIs and have no  guaranteed forward compatibility with the generally available version of the API.  
 *
 * API version: 2.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessagingServiceConnection struct {
	CreatedTime string `json:"createdTime,omitempty"`
	UpdatedTime string `json:"updatedTime,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	ChangedBy string `json:"changedBy,omitempty"`
	// Primary key set by the server.
	Id string `json:"id,omitempty"`
	// The messagingServiceId associated to the connection object.
	MessagingServiceId string `json:"messagingServiceId,omitempty"`
	// The name of the connection object.
	Name string `json:"name,omitempty"`
	// The url of the connection object.
	Url string `json:"url,omitempty"`
	// The protocol of the connection object.
	Protocol string `json:"protocol,omitempty"`
	// The protocolVersion of the connection object.
	ProtocolVersion string `json:"protocolVersion,omitempty"`
	// A JSON map containing a map of connection-specific values. 
	Bindings map[string]interface{} `json:"bindings,omitempty"`
	MessagingServiceAuthentications []MessagingServiceAuthentication `json:"messagingServiceAuthentications,omitempty"`
	Type_ string `json:"type,omitempty"`
}
