/*
 * Event Portal Open API
 *
 * REST API Concepts  Solace PubSub+ Event Portal provides REST APIs that you can use to manage your data in PubSub+ Cloud.  The REST APIs allow you to model your event-driven architectures from your own client applications.  The following document describes the public REST APIs available for use in Event Portal 2.0. Objects created in this  version will not be available in Event Portal 1.0. APIs that display (Beta) in their summary are provided as-is and  are subject to change or removal. They may not be of the quality expected for generally available APIs and have no  guaranteed forward compatibility with the generally available version of the API.  
 *
 * API version: 2.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventVersion struct {
	CreatedTime string `json:"createdTime,omitempty"`
	UpdatedTime string `json:"updatedTime,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	ChangedBy string `json:"changedBy,omitempty"`
	Id string `json:"id,omitempty"`
	EventId string `json:"eventId"`
	Description string `json:"description,omitempty"`
	Version string `json:"version"`
	DisplayName string `json:"displayName,omitempty"`
	DeclaredProducingApplicationVersionIds []string `json:"declaredProducingApplicationVersionIds,omitempty"`
	DeclaredConsumingApplicationVersionIds []string `json:"declaredConsumingApplicationVersionIds,omitempty"`
	ProducingEventApiVersionIds []string `json:"producingEventApiVersionIds,omitempty"`
	ConsumingEventApiVersionIds []string `json:"consumingEventApiVersionIds,omitempty"`
	AttractingApplicationVersionIds []AttractingApplicationVersionTuple `json:"attractingApplicationVersionIds,omitempty"`
	SchemaVersionId string `json:"schemaVersionId,omitempty"`
	SchemaPrimitiveType string `json:"schemaPrimitiveType,omitempty"`
	DeliveryDescriptor *DeliveryDescriptor `json:"deliveryDescriptor,omitempty"`
	StateId string `json:"stateId,omitempty"`
	CustomAttributes []CustomAttribute `json:"customAttributes,omitempty"`
	MessagingServiceIds []string `json:"messagingServiceIds,omitempty"`
	Type_ string `json:"type,omitempty"`
}
