/*
 * Event Portal Open API
 *
 * REST API Concepts  Solace PubSub+ Event Portal provides REST APIs that you can use to manage your data in PubSub+ Cloud.  The REST APIs allow you to model your event-driven architectures from your own client applications.  The following document describes the public REST APIs available for use in Event Portal 2.0. Objects created in this  version will not be available in Event Portal 1.0. APIs that display (Beta) in their summary are provided as-is and  are subject to change or removal. They may not be of the quality expected for generally available APIs and have no  guaranteed forward compatibility with the generally available version of the API.  
 *
 * API version: 2.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Solace class of service policy
type SolaceClassOfServicePolicy struct {
	// ID value of the object
	Id string `json:"id,omitempty"`
	// The type of payload
	Type_ string `json:"type,omitempty"`
	// The mode that will be used for message delivery (ex: `guaranteed` uses a queue)
	MessageDeliveryMode string `json:"messageDeliveryMode,omitempty"`
	AccessType string `json:"accessType,omitempty"`
	// Duration in seconds of how long a message can live in a queue
	MaximumTimeToLive int32 `json:"maximumTimeToLive,omitempty"`
	// The arrangement of queues on a broker used for message delivery (ex: `single` uses one queue per event API version in this event API product)
	QueueType string `json:"queueType,omitempty"`
	// Total number of MBs available for the queue to use
	MaxMsgSpoolUsage int32 `json:"maxMsgSpoolUsage,omitempty"`
}
