/*
 * Event Portal Open API
 *
 * REST API Concepts  Solace PubSub+ Event Portal provides REST APIs that you can use to manage your data in PubSub+ Cloud.  The REST APIs allow you to model your event-driven architectures from your own client applications.  The following document describes the public REST APIs available for use in Event Portal 2.0. Objects created in this  version will not be available in Event Portal 1.0. APIs that display (Beta) in their summary are provided as-is and  are subject to change or removal. They may not be of the quality expected for generally available APIs and have no  guaranteed forward compatibility with the generally available version of the API.  
 *
 * API version: 2.0.11
 * Generated by: Swagger Codegen (https://github.com/eventportal-api/eventportal-codegen.git)
 */
package eventportal

type EventApiProductVersion struct {
	CreatedTime string `json:"createdTime,omitempty"`
	UpdatedTime string `json:"updatedTime,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	ChangedBy string `json:"changedBy,omitempty"`
	Id string `json:"id,omitempty"`
	EventApiProductId string `json:"eventApiProductId"`
	Description string `json:"description,omitempty"`
	Version string `json:"version,omitempty"`
	Summary string `json:"summary,omitempty"`
	CustomAttributes []CustomAttribute `json:"customAttributes,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	// List of IDs of associated event API versions
	EventApiVersionIds []string `json:"eventApiVersionIds,omitempty"`
	StateId string `json:"stateId,omitempty"`
	EventApiProductRegistrations []EventApiProductRegistration `json:"eventApiProductRegistrations,omitempty"`
	Plans []Plan `json:"plans,omitempty"`
	// Solace Messaging Services
	SolaceMessagingServices []SolaceMessagingService `json:"solaceMessagingServices,omitempty"`
	// List of filters that contains eventVersionId name and variables
	Filters []Filter `json:"filters,omitempty"`
	// Approval type
	ApprovalType string `json:"approvalType,omitempty"`
	// The type of payload
	Type_ string `json:"type,omitempty"`
}
